# Radius Recipe manifest for AWS using Terraform

recipes:
  Radius.Compute/containers:
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Compute/containers/recipes/kubernetes/terraform

  Radius.Compute/persistentVolumes:
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Compute/persistentVolumes/recipes/kubernetes/terraform

  Radius.Compute/routes:
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Compute/routes/recipes/kubernetes/terraform

  Radius.Security/secrets:
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Security/secrets/recipes/kubernetes/terraform

  Radius.Data/mySqlDatabases:
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Data/mySqlDatabases/recipes/kubernetes/terraform

  Radius.Data/postgreSqlDatabases:
    recipeKind: terraform
    recipeLocation: git::https://github.com/radius-project/resource-types-contrib.git//Data/postgreSqlDatabases/recipes/kubernetes/terraform
