variable "context" {
  description = "Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.dev/operations/custom-recipes/"
  type        = any
}

variable "storage_class" {
  description = "StorageClass name to set on the PersistentVolumeClaim"
  type        = string
  default     = ""
}

